# Generated by Django 4.2.1 on 2023-05-23 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_options_alter_status_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='PaymentMethod',
        ),
    ]
