# Generated by Django 4.2.1 on 2023-05-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_category_created_at_alter_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='app_carts',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='app_cart_items',
        ),
        migrations.AlterModelTable(
            name='category',
            table='app_categories',
        ),
        migrations.AlterModelTable(
            name='order',
            table='app_orders',
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table='app_payment_methods',
        ),
        migrations.AlterModelTable(
            name='product',
            table='app_products',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='app_ratings',
        ),
        migrations.AlterModelTable(
            name='role',
            table='app_roles',
        ),
        migrations.AlterModelTable(
            name='status',
            table='app_status',
        ),
        migrations.AlterModelTable(
            name='user',
            table='app_users',
        ),
    ]
