# Generated by Django 4.2.1 on 2023-06-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cart_table_alter_cartitem_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
